on:
  release:
        types: [released]
name: Release
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        ./pre-commit.sh
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    needs: [lint]
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: go test ./... -v -coverprofile=${{ matrix.platform }}-coverage.out
    - name: Generate Coverage Report
      run: go tool cover -html=${{ matrix.platform }}-coverage.out -o ${{ matrix.platform }}-coverage.html
    - name: Upload coverage file
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ${{ matrix.platform }}-coverage.html

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
        - uses: actions/checkout@v1
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Update version
          run: echo ${{steps.vars.outputs.tag}} > 'VERSION'
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "mbingo"
            heroku_email: "maneesh.m.babu@gmail.com"
            usedocker: true